stack:
    name: helloworld-security
    system-name: DSO
    master-template: main.yml
    parameters:
        System: {{env:SYSTEM_NAME}}
        Environment: {{env:ENVIRONMENT}}
        Region: {{env:AWS_REGION}}
        ProvisioningBucket: {{env:BUCKET_NAME}}
        ProvisioningBucketPath: cloud-formation
        VPCCIDRBlock: {{input:VPCCIDRBlock}}
        PrivilegedCIDR1: {{input:PrivilegedCIDR1}}
        PrivilegedCIDR2: {{input:PrivilegedCIDR2}}
        PrivilegedCIDR3: {{input:PrivilegedCIDR3}}
        PrivilegedCIDR4: {{input:PrivilegedCIDR4}}
        PrivilegedCIDR5: {{input:PrivilegedCIDR5}}